using Acadimia.Data.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Acadimia.Data.SeedHeper
{
    public static class NationalitySeed
    {
        public static async void Seed(this ModelBuilder builder)
        {
            var nationalities = new List<Nationality>
            {
                new Nationality { Id = 1, NameEn = "Afghan", NameAr = "أفغانستاني" },
                new Nationality { Id = 2, NameEn = "Albanian", NameAr = "ألباني" },
                new Nationality { Id = 3, NameEn = "Aland Islander", NameAr = "آلاندي" },
                new Nationality { Id = 4, NameEn = "Algerian", NameAr = "جزائري" },
                new Nationality { Id = 5, NameEn = "American Samoan", NameAr = "أمريكي سامواني" },
                new Nationality { Id = 6, NameEn = "Andorran", NameAr = "أندوري" },
                new Nationality { Id = 7, NameEn = "Angolan", NameAr = "أنقولي" },
                new Nationality { Id = 8, NameEn = "Anguillan", NameAr = "أنغويلي" },
                new Nationality { Id = 9, NameEn = "Antarctican", NameAr = "أنتاركتيكي" },
                new Nationality { Id = 10, NameEn = "Antiguan", NameAr = "بربودي" },
                new Nationality { Id = 11, NameEn = "Argentinian", NameAr = "أرجنتيني" },
                new Nationality { Id = 12, NameEn = "Armenian", NameAr = "أرميني" },
                new Nationality { Id = 13, NameEn = "Aruban", NameAr = "أوروبهيني" },
                new Nationality { Id = 14, NameEn = "Australian", NameAr = "أسترالي" },
                new Nationality { Id = 15, NameEn = "Austrian", NameAr = "نمساوي" },
                new Nationality { Id = 16, NameEn = "Azerbaijani", NameAr = "أذربيجاني" },
                new Nationality { Id = 17, NameEn = "Bahamian", NameAr = "باهاميسي" },
                new Nationality { Id = 18, NameEn = "Bahraini", NameAr = "بحريني" },
                new Nationality { Id = 19, NameEn = "Bangladeshi", NameAr = "بنغلاديشي" },
                new Nationality { Id = 20, NameEn = "Barbadian", NameAr = "بربادوسي" },
                new Nationality { Id = 21, NameEn = "Belarusian", NameAr = "روسي" },
                new Nationality { Id = 22, NameEn = "Belgian", NameAr = "بلجيكي" },
                new Nationality { Id = 23, NameEn = "Belizean", NameAr = "بيليزي" },
                new Nationality { Id = 24, NameEn = "Beninese", NameAr = "بنيني" },
                new Nationality { Id = 25, NameEn = "Saint Barthelmian", NameAr = "سان بارتيلمي" },
                new Nationality { Id = 26, NameEn = "Bermudan", NameAr = "برمودي" },
                new Nationality { Id = 27, NameEn = "Bhutanese", NameAr = "بوتاني" },
                new Nationality { Id = 28, NameEn = "Bolivian", NameAr = "بوليفي" },
                new Nationality { Id = 29, NameEn = "Bosnian / Herzegovinian", NameAr = "بوسني/هرسكي" },
                new Nationality { Id = 30, NameEn = "Botswanan", NameAr = "بوتسواني" },
                new Nationality { Id = 31, NameEn = "Bouvetian", NameAr = "بوفيهي" },
                new Nationality { Id = 32, NameEn = "Brazilian", NameAr = "برازيلي" },
                new Nationality { Id = 33, NameEn = "British Indian Ocean Territory", NameAr = "إقليم المحيط الهندي البريطاني" },
                new Nationality { Id = 34, NameEn = "Bruneian", NameAr = "بروني" },
                new Nationality { Id = 35, NameEn = "Bulgarian", NameAr = "بلغاري" },
                new Nationality { Id = 36, NameEn = "Burkinabe", NameAr = "بوركيني" },
                new Nationality { Id = 37, NameEn = "Burundian", NameAr = "بورونيدي" },
                new Nationality { Id = 38, NameEn = "Cambodian", NameAr = "كمبودي" },
                new Nationality { Id = 39, NameEn = "Cameroonian", NameAr = "كاميروني" },
                new Nationality { Id = 40, NameEn = "Canadian", NameAr = "كندي" },
                new Nationality { Id = 41, NameEn = "Cape Verdean", NameAr = "الرأس الأخضر" },
                new Nationality { Id = 42, NameEn = "Caymanian", NameAr = "كايماني" },
                new Nationality { Id = 43, NameEn = "Central African", NameAr = "أفريقي" },
                new Nationality { Id = 44, NameEn = "Chadian", NameAr = "تشادي" },
                new Nationality { Id = 45, NameEn = "Chilean", NameAr = "شيلي" },
                new Nationality { Id = 46, NameEn = "Chinese", NameAr = "صيني" },
                new Nationality { Id = 47, NameEn = "Christmas Islander", NameAr = "جزيرة عيد الميلاد" },
                new Nationality { Id = 48, NameEn = "Cocos Islander", NameAr = "جزر كوكوس" },
                new Nationality { Id = 49, NameEn = "Colombian", NameAr = "كولومبي" },
                new Nationality { Id = 50, NameEn = "Comorian", NameAr = "جزر القمر" },
                new Nationality { Id = 51, NameEn = "Congolese", NameAr = "كونغي" },
                new Nationality { Id = 52, NameEn = "Cook Islander", NameAr = "جزر كوك" },
                new Nationality { Id = 53, NameEn = "Costa Rican", NameAr = "كوستاريكي" },
                new Nationality { Id = 54, NameEn = "Croatian", NameAr = "كوراتي" },
                new Nationality { Id = 55, NameEn = "Cuban", NameAr = "كوبي" },
                new Nationality { Id = 56, NameEn = "Cypriot", NameAr = "قبرصي" },
                new Nationality { Id = 57, NameEn = "Curacian", NameAr = "كوراساوي" },
                new Nationality { Id = 58, NameEn = "Czech", NameAr = "تشيكي" },
                new Nationality { Id = 59, NameEn = "Danish", NameAr = "دنماركي" },
                new Nationality { Id = 60, NameEn = "Djiboutian", NameAr = "جيبوتي" },
                new Nationality { Id = 61, NameEn = "Dominican", NameAr = "دومينيكي" },
                new Nationality { Id = 62, NameEn = "Dominican", NameAr = "دومينيكي" },
                new Nationality { Id = 63, NameEn = "Ecuadorian", NameAr = "إكوادوري" },
                new Nationality { Id = 64, NameEn = "Egyptian", NameAr = "مصري" },
                new Nationality { Id = 65, NameEn = "Salvadoran", NameAr = "سلفادوري" },
                new Nationality { Id = 66, NameEn = "Equatorial Guinean", NameAr = "غيني" },
                new Nationality { Id = 67, NameEn = "Eritrean", NameAr = "إريتيري" },
                new Nationality { Id = 68, NameEn = "Estonian", NameAr = "استوني" },
                new Nationality { Id = 69, NameEn = "Ethiopian", NameAr = "أثيوبي" },
                new Nationality { Id = 70, NameEn = "Falkland Islander", NameAr = "فوكلاندي" },
                new Nationality { Id = 71, NameEn = "Faroese", NameAr = "جزر فارو" },
                new Nationality { Id = 72, NameEn = "Fijian", NameAr = "فيجي" },
                new Nationality { Id = 73, NameEn = "Finnish", NameAr = "فنلندي" },
                new Nationality { Id = 74, NameEn = "French", NameAr = "فرنسي" },
                new Nationality { Id = 75, NameEn = "French Guianese", NameAr = "غويانا الفرنسية" },
                new Nationality { Id = 76, NameEn = "French Polynesian", NameAr = "بولينيزيي" },
                new Nationality { Id = 77, NameEn = "French", NameAr = "أراض فرنسية جنوبية وأنتارتيكية" },
                new Nationality { Id = 78, NameEn = "Gabonese", NameAr = "غابوني" },
                new Nationality { Id = 79, NameEn = "Gambian", NameAr = "غامبي" },
                new Nationality { Id = 80, NameEn = "Georgian", NameAr = "جيورجي" },
                new Nationality { Id = 81, NameEn = "German", NameAr = "ألماني" },
                new Nationality { Id = 82, NameEn = "Ghanaian", NameAr = "غاني" },
                new Nationality { Id = 83, NameEn = "Gibraltar", NameAr = "جبل طارق" },
                new Nationality { Id = 84, NameEn = "Guernsian", NameAr = "غيرنزي" },
                new Nationality { Id = 85, NameEn = "Greek", NameAr = "يوناني" },
                new Nationality { Id = 86, NameEn = "Greenlandic", NameAr = "جرينلاندي" },
                new Nationality { Id = 87, NameEn = "Grenadian", NameAr = "غرينادي" },
                new Nationality { Id = 88, NameEn = "Guadeloupe", NameAr = "جزر جوادلوب" },
                new Nationality { Id = 89, NameEn = "Guamanian", NameAr = "جوامي" },
                new Nationality { Id = 90, NameEn = "Guatemalan", NameAr = "غواتيمالي" },
                new Nationality { Id = 91, NameEn = "Guinean", NameAr = "غيني" },
                new Nationality { Id = 92, NameEn = "Guinea-Bissauan", NameAr = "غيني" },
                new Nationality { Id = 93, NameEn = "Guyanese", NameAr = "غياني" },
                new Nationality { Id = 94, NameEn = "Haitian", NameAr = "هايتي" },
                new Nationality { Id = 95, NameEn = "Heard and Mc Donald Islanders", NameAr = "جزيرة هيرد وجزر ماكدونالد" },
                new Nationality { Id = 96, NameEn = "Honduran", NameAr = "هندوراسي" },
                new Nationality { Id = 97, NameEn = "Hongkongese", NameAr = "هونغ كونغي" },
                new Nationality { Id = 98, NameEn = "Hungarian", NameAr = "مجري" },
                new Nationality { Id = 99, NameEn = "Icelandic", NameAr = "آيسلندي" },
                new Nationality { Id = 100, NameEn = "Indian", NameAr = "هندي" },
                new Nationality { Id = 101, NameEn = "Manx", NameAr = "ماني" },
                new Nationality { Id = 102, NameEn = "Indonesian", NameAr = "أندونيسيي" },
                new Nationality { Id = 103, NameEn = "Iranian", NameAr = "إيراني" },
                new Nationality { Id = 104, NameEn = "Iraqi", NameAr = "عراقي" },
                new Nationality { Id = 105, NameEn = "Irish", NameAr = "إيرلندي" },
                new Nationality { Id = 106, NameEn = "Israeli", NameAr = "إسرائيلي" },
                new Nationality { Id = 107, NameEn = "Italian", NameAr = "إيطالي" },
                new Nationality { Id = 108, NameEn = "Ivory Coastian", NameAr = "ساحل العاج" },
                new Nationality { Id = 109, NameEn = "Jersian", NameAr = "جيرزي" },
                new Nationality { Id = 110, NameEn = "Jamaican", NameAr = "جمايكي" },
                new Nationality { Id = 111, NameEn = "Japanese", NameAr = "ياباني" },
                new Nationality { Id = 112, NameEn = "Jordanian", NameAr = "أردني" },
                new Nationality { Id = 113, NameEn = "Kazakh", NameAr = "كازاخستاني" },
                new Nationality { Id = 114, NameEn = "Kenyan", NameAr = "كيني" },
                new Nationality { Id = 115, NameEn = "I-Kiribati", NameAr = "كيريباتي" },
                new Nationality { Id = 116, NameEn = "North Korean", NameAr = "كوري" },
                new Nationality { Id = 117, NameEn = "South Korean", NameAr = "كوري" },
                new Nationality { Id = 118, NameEn = "Kosovar", NameAr = "كوسيفي" },
                new Nationality { Id = 119, NameEn = "Kuwaiti", NameAr = "كويتي" },
                new Nationality { Id = 120, NameEn = "Kyrgyzstani", NameAr = "قيرغيزستاني" },
                new Nationality { Id = 121, NameEn = "Laotian", NameAr = "لاوسي" },
                new Nationality { Id = 122, NameEn = "Latvian", NameAr = "لاتيفي" },
                new Nationality { Id = 123, NameEn = "Lebanese", NameAr = "لبناني" },
                new Nationality { Id = 124, NameEn = "Basotho", NameAr = "ليوسيتي" },
                new Nationality { Id = 125, NameEn = "Liberian", NameAr = "ليبيري" },
                new Nationality { Id = 126, NameEn = "Libyan", NameAr = "ليبي" },
                new Nationality { Id = 127, NameEn = "Liechtenstein", NameAr = "ليختنشتيني" },
                new Nationality { Id = 128, NameEn = "Lithuanian", NameAr = "لتوانيي" },
                new Nationality { Id = 129, NameEn = "Luxembourger", NameAr = "لوكسمبورغي" },
                new Nationality { Id = 130, NameEn = "Sri Lankian", NameAr = "سريلانكي" },
                new Nationality { Id = 131, NameEn = "Macanese", NameAr = "ماكاوي" },
                new Nationality { Id = 132, NameEn = "Macedonian", NameAr = "مقدوني" },
                new Nationality { Id = 133, NameEn = "Malagasy", NameAr = "مدغشقري" },
                new Nationality { Id = 134, NameEn = "Malawian", NameAr = "مالاوي" },
                new Nationality { Id = 135, NameEn = "Malaysian", NameAr = "ماليزي" },
                new Nationality { Id = 136, NameEn = "Maldivian", NameAr = "مالديفي" },
                new Nationality { Id = 137, NameEn = "Malian", NameAr = "مالي" },
                new Nationality { Id = 138, NameEn = "Maltese", NameAr = "مالطي" },
                new Nationality { Id = 139, NameEn = "Marshallese", NameAr = "مارشالي" },
                new Nationality { Id = 140, NameEn = "Martiniquais", NameAr = "مارتينيكي" },
                new Nationality { Id = 141, NameEn = "Mauritanian", NameAr = "موريتانيي" },
                new Nationality { Id = 142, NameEn = "Mauritian", NameAr = "موريشيوسي" },
                new Nationality { Id = 143, NameEn = "Mahoran", NameAr = "مايوتي" },
                new Nationality { Id = 144, NameEn = "Mexican", NameAr = "مكسيكي" },
                new Nationality { Id = 145, NameEn = "Micronesian", NameAr = "مايكرونيزيي" },
                new Nationality { Id = 146, NameEn = "Moldovan", NameAr = "مولديفي" },
                new Nationality { Id = 147, NameEn = "Monacan", NameAr = "مونيكي" },
                new Nationality { Id = 148, NameEn = "Mongolian", NameAr = "منغولي" },
                new Nationality { Id = 149, NameEn = "Montenegrin", NameAr = "الجبل الأسود" },
                new Nationality { Id = 150, NameEn = "Montserratian", NameAr = "مونتسيراتي" },
                new Nationality { Id = 151, NameEn = "Moroccan", NameAr = "مغربي" },
                new Nationality { Id = 152, NameEn = "Mozambican", NameAr = "موزمبيقي" },
                new Nationality { Id = 153, NameEn = "Myanmarian", NameAr = "ميانماري" },
                new Nationality { Id = 154, NameEn = "Namibian", NameAr = "ناميبي" },
                new Nationality { Id = 155, NameEn = "Nauruan", NameAr = "نوري" },
                new Nationality { Id = 156, NameEn = "Nepalese", NameAr = "نيبالي" },
                new Nationality { Id = 157, NameEn = "Dutch", NameAr = "هولندي" },
                new Nationality { Id = 158, NameEn = "Dutch Antilier", NameAr = "هولندي" },
                new Nationality { Id = 159, NameEn = "New Caledonian", NameAr = "كاليدونيا" },
                new Nationality { Id = 160, NameEn = "New Zealander", NameAr = "نيوزيلندي" },
                new Nationality { Id = 161, NameEn = "Nicaraguan", NameAr = "نيكاراجوي" },
                new Nationality { Id = 162, NameEn = "Nigerien", NameAr = "نيجيري" },
                new Nationality { Id = 163, NameEn = "Nigerian", NameAr = "نيجيري" },
                new Nationality { Id = 164, NameEn = "Niuean", NameAr = "ني" },
                new Nationality { Id = 165, NameEn = "Norfolk Islander", NameAr = "نورفوليكي" },
                new Nationality { Id = 166, NameEn = "Northern Marianan", NameAr = "ماريني" },
                new Nationality { Id = 167, NameEn = "Norwegian", NameAr = "نرويجي" },
                new Nationality { Id = 168, NameEn = "Omani", NameAr = "عماني" },
                new Nationality { Id = 169, NameEn = "Pakistani", NameAr = "باكستاني" },
                new Nationality { Id = 170, NameEn = "Palauan", NameAr = "بالاوي" },
                new Nationality { Id = 171, NameEn = "Palestinian", NameAr = "فلسطيني" },
                new Nationality { Id = 172, NameEn = "Panamanian", NameAr = "بنمي" },
                new Nationality { Id = 173, NameEn = "Papua New Guinean", NameAr = "بابوي" },
                new Nationality { Id = 174, NameEn = "Paraguayan", NameAr = "بارغاوي" },
                new Nationality { Id = 175, NameEn = "Peruvian", NameAr = "بيري" },
                new Nationality { Id = 176, NameEn = "Filipino", NameAr = "فلبيني" },
                new Nationality { Id = 177, NameEn = "Pitcairn Islander", NameAr = "بيتكيرني" },
                new Nationality { Id = 178, NameEn = "Polish", NameAr = "بولندي" },
                new Nationality { Id = 179, NameEn = "Portuguese", NameAr = "برتغالي" },
                new Nationality { Id = 180, NameEn = "Puerto Rican", NameAr = "بورتي" },
                new Nationality { Id = 181, NameEn = "Qatari", NameAr = "قطري" },
                new Nationality { Id = 182, NameEn = "Reunionese", NameAr = "ريونيوني" },
                new Nationality { Id = 183, NameEn = "Romanian", NameAr = "روماني" },
                new Nationality { Id = 184, NameEn = "Russian", NameAr = "روسي" },
                new Nationality { Id = 185, NameEn = "Rwandan", NameAr = "رواندا" },
                new Nationality { Id = 186, NameEn = "Kittitian/Nevisian", NameAr = "سانت كيتس ونيفس" },
                new Nationality { Id = 187, NameEn = "St. Martian(French)", NameAr = "ساينت مارتني فرنسي" },
                new Nationality { Id = 188, NameEn = "St. Martian(Dutch)", NameAr = "ساينت مارتني هولندي" },
                new Nationality { Id = 189, NameEn = "St. Pierre and Miquelon", NameAr = "سان بيير وميكلوني" },
                new Nationality { Id = 190, NameEn = "Saint Vincent and the Grenadines", NameAr = "سانت فنسنت وجزر غرينادين" },
                new Nationality { Id = 191, NameEn = "Samoan", NameAr = "ساموي" },
                new Nationality { Id = 192, NameEn = "Sammarinese", NameAr = "ماريني" },
                new Nationality { Id = 193, NameEn = "Sao Tomean", NameAr = "ساو تومي وبرينسيبي" },
                new Nationality { Id = 194, NameEn = "Saudi Arabian", NameAr = "سعودي" },
                new Nationality { Id = 195, NameEn = "Senegalese", NameAr = "سنغالي" },
                new Nationality { Id = 196, NameEn = "Serbian", NameAr = "صربي" },
                new Nationality { Id = 197, NameEn = "Seychellois", NameAr = "سيشيلي" },
                new Nationality { Id = 198, NameEn = "Sierra Leonean", NameAr = "سيراليوني" },
                new Nationality { Id = 199, NameEn = "Singaporean", NameAr = "سنغافوري" },
                new Nationality { Id = 200, NameEn = "Slovak", NameAr = "سولفاكي" },
                new Nationality { Id = 201, NameEn = "Slovenian", NameAr = "سولفيني" },
                new Nationality { Id = 202, NameEn = "Solomon Island", NameAr = "جزر سليمان" },
                new Nationality { Id = 203, NameEn = "Somali", NameAr = "صومالي" },
                new Nationality { Id = 204, NameEn = "South African", NameAr = "أفريقي" },
                new Nationality { Id = 205, NameEn = "South Georgia and the South Sandwich", NameAr = "لمنطقة القطبية الجنوبية" },
                new Nationality { Id = 206, NameEn = "South Sudanese", NameAr = "سوادني جنوبي" },
                new Nationality { Id = 207, NameEn = "Spanish", NameAr = "إسباني" },
                new Nationality { Id = 208, NameEn = "St. Helenian", NameAr = "هيلاني" },
                new Nationality { Id = 209, NameEn = "Sudanese", NameAr = "سوداني" },
                new Nationality { Id = 210, NameEn = "Surinamese", NameAr = "سورينامي" },
                new Nationality { Id = 211, NameEn = "Svalbardian/Jan Mayenian", NameAr = "سفالبارد ويان ماين" },
                new Nationality { Id = 212, NameEn = "Swazi", NameAr = "سوازيلندي" },
                new Nationality { Id = 213, NameEn = "Swedish", NameAr = "سويدي" },
                new Nationality { Id = 214, NameEn = "Swiss", NameAr = "سويسري" },
                new Nationality { Id = 215, NameEn = "Syrian", NameAr = "سوري" },
                new Nationality { Id = 216, NameEn = "Taiwanese", NameAr = "تايواني" },
                new Nationality { Id = 217, NameEn = "Tajikistani", NameAr = "طاجيكستاني" },
                new Nationality { Id = 218, NameEn = "Tanzanian", NameAr = "تنزانيي" },
                new Nationality { Id = 219, NameEn = "Thai", NameAr = "تايلندي" },
                new Nationality { Id = 220, NameEn = "Timor-Lestian", NameAr = "تيموري" },
                new Nationality { Id = 221, NameEn = "Togolese", NameAr = "توغي" },
                new Nationality { Id = 222, NameEn = "Tokelaian", NameAr = "توكيلاوي" },
                new Nationality { Id = 223, NameEn = "Tongan", NameAr = "تونغي" },
                new Nationality { Id = 224, NameEn = "Trinidadian/Tobagonian", NameAr = "ترينيداد وتوباغو" },
                new Nationality { Id = 225, NameEn = "Tunisian", NameAr = "تونسي" },
                new Nationality { Id = 226, NameEn = "Turkish", NameAr = "تركي" },
                new Nationality { Id = 227, NameEn = "Turkmen", NameAr = "تركمانستاني" },
                new Nationality { Id = 228, NameEn = "Turks and Caicos Islands", NameAr = "جزر توركس وكايكوس" },
                new Nationality { Id = 229, NameEn = "Tuvaluan", NameAr = "توفالي" },
                new Nationality { Id = 230, NameEn = "Ugandan", NameAr = "أوغندي" },
                new Nationality { Id = 231, NameEn = "Ukrainian", NameAr = "أوكراني" },
                new Nationality { Id = 232, NameEn = "Emirati", NameAr = "إماراتي" },
                new Nationality { Id = 233, NameEn = "British", NameAr = "بريطاني" },
                new Nationality { Id = 234, NameEn = "American", NameAr = "أمريكي" },
                new Nationality { Id = 235, NameEn = "US Minor Outlying Islander", NameAr = "أمريكي" },
                new Nationality { Id = 236, NameEn = "Uruguayan", NameAr = "أورغواي" },
                new Nationality { Id = 237, NameEn = "Uzbek", NameAr = "أوزباكستاني" },
                new Nationality { Id = 238, NameEn = "Vanuatuan", NameAr = "فانواتي" },
                new Nationality { Id = 239, NameEn = "Venezuelan", NameAr = "فنزويلي" },
                new Nationality { Id = 240, NameEn = "Vietnamese", NameAr = "فيتنامي" },
                new Nationality { Id = 241, NameEn = "American Virgin Islander", NameAr = "أمريكي" },
                new Nationality { Id = 242, NameEn = "Vatican", NameAr = "فاتيكاني" },
                new Nationality { Id = 243, NameEn = "Wallisian/Futunan", NameAr = "فوتوني" },
                new Nationality { Id = 244, NameEn = "Sahrawian", NameAr = "صحراوي" },
                new Nationality { Id = 245, NameEn = "Yemeni", NameAr = "يمني" },
                new Nationality { Id = 246, NameEn = "Zambian", NameAr = "زامبياني" },
                new Nationality { Id = 247, NameEn = "Zimbabwean", NameAr = "زمبابوي" }
            };

            builder.Entity<Nationality>().HasData(nationalities);
        }
    }
}
