using Acadimia.Data.Models;

namespace Acadimia.Data.SeedHeper
{
    public static class NationalityData
    {
        public static List<Nationality> All => new()
        {
            N(1,"Afghan","أفغانستاني"), N(2,"Albanian","ألباني"), N(3,"Aland Islander","آلاندي"),
            N(4,"Algerian","جزائري"), N(5,"American Samoan","أمريكي سامواني"), N(6,"Andorran","أندوري"),
            N(7,"Angolan","أنغولي"), N(8,"Anguillan","أنغويلي"), N(9,"Antarctican","أنتاركتيكي"),
            N(10,"Antiguan","أنتيغوي"), N(11,"Argentinian","أرجنتيني"), N(12,"Armenian","أرميني"),
            N(13,"Aruban","أروبي"), N(14,"Australian","أسترالي"), N(15,"Austrian","نمساوي"),
            N(16,"Azerbaijani","أذربيجاني"), N(17,"Bahamian","باهاميسي"), N(18,"Bahraini","بحريني"),
            N(19,"Bangladeshi","بنغلاديشي"), N(20,"Barbadian","بربادوسي"), N(21,"Belarusian","بيلاروسي"),
            N(22,"Belgian","بلجيكي"), N(23,"Belizean","بيليزي"), N(24,"Beninese","بنيني"),
            N(25,"Saint Barthelmian","سان بارتيلمي"), N(26,"Bermudan","برمودي"), N(27,"Bhutanese","بوتاني"),
            N(28,"Bolivian","بوليفي"), N(29,"Bosnian / Herzegovinian","بوسني/هرسكي"), N(30,"Botswanan","بوتسواني"),
            N(31,"Bouvetian","بوفيهي"), N(32,"Brazilian","برازيلي"),
            N(33,"British Indian Ocean Territory","إقليم المحيط الهندي البريطاني"), N(34,"Bruneian","بروني"),
            N(35,"Bulgarian","بلغاري"), N(36,"Burkinabe","بوركيني"), N(37,"Burundian","بورونيدي"),
            N(38,"Cambodian","كمبودي"), N(39,"Cameroonian","كاميروني"), N(40,"Canadian","كندي"),
            N(41,"Cape Verdean","الرأس الأخضر"), N(42,"Caymanian","كايماني"), N(43,"Central African","إفريقي أوسط"),
            N(44,"Chadian","تشادي"), N(45,"Chilean","تشيلي"), N(46,"Chinese","صيني"),
            N(47,"Christmas Islander","جزيرة عيد الميلاد"), N(48,"Cocos Islander","جزر كوكوس"),
            N(49,"Colombian","كولومبي"), N(50,"Comorian","جزر القمر"), N(51,"Congolese","كونغولي"),
            N(52,"Cook Islander","جزر كوك"), N(53,"Costa Rican","كوستاريكي"), N(54,"Croatian","كرواتي"),
            N(55,"Cuban","كوبي"), N(56,"Cypriot","قبرصي"), N(57,"Curacian","كوراساوي"),
            N(58,"Czech","تشيكي"), N(59,"Danish","دنماركي"), N(60,"Djiboutian","جيبوتي"),
            N(61,"Dominican","دومينيكي"), N(62,"Dominican (Republic)","دومينيكاني"),
            N(63,"Ecuadorian","إكوادوري"), N(64,"Egyptian","مصري"), N(65,"Salvadoran","سلفادوري"),
            N(66,"Equatorial Guinean","غيني استوائي"), N(67,"Eritrean","إريتيري"), N(68,"Estonian","إستوني"),
            N(69,"Ethiopian","إثيوبي"), N(70,"Falkland Islander","فوكلاندي"), N(71,"Faroese","جزر فارو"),
            N(72,"Fijian","فيجي"), N(73,"Finnish","فنلندي"), N(74,"French","فرنسي"),
            N(75,"French Guianese","غويانا الفرنسية"), N(76,"French Polynesian","بولينيزي"),
            N(77,"French Southern Territories","أراض فرنسية جنوبية وأنتاركتيكية"), N(78,"Gabonese","غابوني"),
            N(79,"Gambian","غامبي"), N(80,"Georgian","جورجي"), N(81,"German","ألماني"),
            N(82,"Ghanaian","غاني"), N(83,"Gibraltar","جبل طارق"), N(84,"Guernsian","غيرنزي"),
            N(85,"Greek","يوناني"), N(86,"Greenlandic","غرينلاندي"), N(87,"Grenadian","غرينادي"),
            N(88,"Guadeloupe","جزر جوادلوب"), N(89,"Guamanian","جوامي"), N(90,"Guatemalan","غواتيمالي"),
            N(91,"Guinean","غيني"), N(92,"Guinea-Bissauan","غيني بيساوي"), N(93,"Guyanese","غياني"),
            N(94,"Haitian","هايتي"), N(95,"Heard and Mc Donald Islanders","جزيرة هيرد وجزر ماكدونالد"),
            N(96,"Honduran","هندوراسي"), N(97,"Hongkongese","هونغ كونغي"), N(98,"Hungarian","مجري"),
            N(99,"Icelandic","آيسلندي"), N(100,"Indian","هندي"), N(101,"Manx","ماني"),
            N(102,"Indonesian","إندونيسي"), N(103,"Iranian","إيراني"), N(104,"Iraqi","عراقي"),
            N(105,"Irish","إيرلندي"), N(106,"Israeli","إسرائيلي"), N(107,"Italian","إيطالي"),
            N(108,"Ivory Coastian","ساحل العاج"), N(109,"Jersian","جيرزي"), N(110,"Jamaican","جمايكي"),
            N(111,"Japanese","ياباني"), N(112,"Jordanian","أردني"), N(113,"Kazakh","كازاخستاني"),
            N(114,"Kenyan","كيني"), N(115,"I-Kiribati","كيريباتي"), N(116,"North Korean","كوري شمالي"),
            N(117,"South Korean","كوري جنوبي"), N(118,"Kosovar","كوسوفي"), N(119,"Kuwaiti","كويتي"),
            N(120,"Kyrgyzstani","قيرغيزستاني"), N(121,"Laotian","لاوسي"), N(122,"Latvian","لاتفي"),
            N(123,"Lebanese","لبناني"), N(124,"Basotho","ليسوتي"), N(125,"Liberian","ليبيري"),
            N(126,"Libyan","ليبي"), N(127,"Liechtenstein","ليختنشتيني"), N(128,"Lithuanian","ليتواني"),
            N(129,"Luxembourger","لوكسمبورغي"), N(130,"Sri Lankian","سريلانكي"), N(131,"Macanese","ماكاوي"),
            N(132,"Macedonian","مقدوني"), N(133,"Malagasy","مدغشقري"), N(134,"Malawian","مالاوي"),
            N(135,"Malaysian","ماليزي"), N(136,"Maldivian","مالديفي"), N(137,"Malian","مالي"),
            N(138,"Maltese","مالطي"), N(139,"Marshallese","مارشالي"), N(140,"Martiniquais","مارتينيكي"),
            N(141,"Mauritanian","موريتاني"), N(142,"Mauritian","موريشيوسي"), N(143,"Mahoran","مايوتي"),
            N(144,"Mexican","مكسيكي"), N(145,"Micronesian","ميكرونيزي"), N(146,"Moldovan","مولدوفي"),
            N(147,"Monacan","موناكي"), N(148,"Mongolian","منغولي"), N(149,"Montenegrin","الجبل الأسود"),
            N(150,"Montserratian","مونتسيراتي"), N(151,"Moroccan","مغربي"), N(152,"Mozambican","موزمبيقي"),
            N(153,"Myanmarian","ميانماري"), N(154,"Namibian","ناميبي"), N(155,"Nauruan","ناوروي"),
            N(156,"Nepalese","نيبالي"), N(157,"Dutch","هولندي"), N(158,"Dutch Antilier","أنتيلي هولندي"),
            N(159,"New Caledonian","كاليدوني"), N(160,"New Zealander","نيوزيلندي"), N(161,"Nicaraguan","نيكاراغوي"),
            N(162,"Nigerien","نيجري"), N(163,"Nigerian","نيجيري"), N(164,"Niuean","نيوي"),
            N(165,"Norfolk Islander","نورفوليكي"), N(166,"Northern Marianan","ماريانا الشمالية"),
            N(167,"Norwegian","نرويجي"), N(168,"Omani","عماني"), N(169,"Pakistani","باكستاني"),
            N(170,"Palauan","بالاوي"), N(171,"Palestinian","فلسطيني"), N(172,"Panamanian","بنمي"),
            N(173,"Papua New Guinean","بابوي"), N(174,"Paraguayan","باراغوياني"), N(175,"Peruvian","بيروفي"),
            N(176,"Filipino","فلبيني"), N(177,"Pitcairn Islander","بيتكيرني"), N(178,"Polish","بولندي"),
            N(179,"Portuguese","برتغالي"), N(180,"Puerto Rican","بورتوريكي"), N(181,"Qatari","قطري"),
            N(182,"Reunionese","ريونيوني"), N(183,"Romanian","روماني"), N(184,"Russian","روسي"),
            N(185,"Rwandan","رواندي"), N(186,"Kittitian/Nevisian","سانت كيتس ونيفس"),
            N(187,"St. Martian(French)","ساينت مارتن الفرنسية"), N(188,"St. Martian(Dutch)","ساينت مارتن الهولندية"),
            N(189,"St. Pierre and Miquelon","سان بيير وميكلون"),
            N(190,"Saint Vincent and the Grenadines","سانت فنسنت وجزر غرينادين"), N(191,"Samoan","ساموي"),
            N(192,"Sammarinese","سان مارينو"), N(193,"Sao Tomean","ساو تومي وبرينسيبي"),
            N(194,"Saudi Arabian","سعودي"), N(195,"Senegalese","سنغالي"), N(196,"Serbian","صربي"),
            N(197,"Seychellois","سيشيلي"), N(198,"Sierra Leonean","سيراليوني"), N(199,"Singaporean","سنغافوري"),
            N(200,"Slovak","سلوفاكي"), N(201,"Slovenian","سلوفيني"), N(202,"Solomon Island","جزر سليمان"),
            N(203,"Somali","صومالي"), N(204,"South African","جنوب إفريقي"),
            N(205,"South Georgia and the South Sandwich","جورجيا الجنوبية وساندويتش الجنوبية"),
            N(206,"South Sudanese","جنوب سوداني"), N(207,"Spanish","إسباني"), N(208,"St. Helenian","هيلاني"),
            N(209,"Sudanese","سوداني"), N(210,"Surinamese","سورينامي"),
            N(211,"Svalbardian/Jan Mayenian","سفالبارد ويان ماين"), N(212,"Swazi","سوازيلندي"),
            N(213,"Swedish","سويدي"), N(214,"Swiss","سويسري"), N(215,"Syrian","سوري"),
            N(216,"Taiwanese","تايواني"), N(217,"Tajikistani","طاجيكستاني"), N(218,"Tanzanian","تنزاني"),
            N(219,"Thai","تايلندي"), N(220,"Timor-Lestian","تيموري"), N(221,"Togolese","توغولي"),
            N(222,"Tokelaian","توكيلاوي"), N(223,"Tongan","تونغي"),
            N(224,"Trinidadian/Tobagonian","ترينيداد وتوباغو"), N(225,"Tunisian","تونسي"),
            N(226,"Turkish","تركي"), N(227,"Turkmen","تركمانستاني"),
            N(228,"Turks and Caicos Islands","جزر توركس وكايكوس"), N(229,"Tuvaluan","توفالي"),
            N(230,"Ugandan","أوغندي"), N(231,"Ukrainian","أوكراني"), N(232,"Emirati","إماراتي"),
            N(233,"British","بريطاني"), N(234,"American","أمريكي"),
            N(235,"US Minor Outlying Islander","جزر الولايات المتحدة الصغيرة"), N(236,"Uruguayan","أوروغواياني"),
            N(237,"Uzbek","أوزبكستاني"), N(238,"Vanuatuan","فانواتي"), N(239,"Venezuelan","فنزويلي"),
            N(240,"Vietnamese","فيتنامي"), N(241,"American Virgin Islander","جزر العذراء الأمريكية"),
            N(242,"Vatican","فاتيكاني"), N(243,"Wallisian/Futunan","واليس وفوتونا"),
            N(244,"Sahrawian","صحراوي"), N(245,"Yemeni","يمني"), N(246,"Zambian","زامبي"),
            N(247,"Zimbabwean","زيمبابوي"),
        };

        private static Nationality N(int id, string en, string ar) =>
            new() { Id = id, NameEn = en, NameAr = ar };
    }
}